import { pgTable, uuid, varchar, text, boolean, timestamp, integer, bigint, decimal } from 'drizzle-orm/pg-core'
import { relations } from 'drizzle-orm'

export const rolesTable = pgTable('roles', {
    roleId: integer('role_id').primaryKey().generatedAlwaysAsIdentity(),
    roleName: varchar('role_name', { length: 100 }).notNull(),
    company: varchar('company', { length: 100 }),
    createdAt: timestamp('created_at').defaultNow(),
    updatedAt: timestamp('updated_at').$onUpdate(() => new Date()),
})

export const usersTable = pgTable('users', {
    id: uuid('id').primaryKey().defaultRandom(),

    firstName: varchar('first_name', { length: 45 }).notNull(),
    lastName: varchar('last_name', { length: 45 }),

    email: varchar('email', { length: 322 }).notNull().unique(),
    emailVerified: boolean('email_verified').default(false).notNull(),

    password: varchar('password', { length: 66 }),
    salt: text('salt'),

    roleId: integer('role_id').references(() => rolesTable.roleId),
    isAdmin: boolean('is_admin').default(false).notNull(),
    adminRequested: boolean('admin_requested').default(false).notNull(),
    accountStatus: varchar('account_status', { length: 20 }).default('pending').notNull(),
    company: varchar('company', { length: 100 }),

    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at').$onUpdate(() => new Date()),
})

export const sessionsTable = pgTable('sessions', {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id').notNull().references(() => usersTable.id, { onDelete: 'cascade' }),
    token: text('token').notNull().unique(),
    expiresAt: timestamp('expires_at').notNull(),
    createdAt: timestamp('created_at').defaultNow().notNull(),
})

export const companyTable = pgTable('Company', {
    CompanyID: integer('CompanyID').primaryKey().generatedAlwaysAsIdentity(),
    Name: varchar('Name', { length: 255 }).notNull(),
    Address: text('Address'),
    GSTIN: varchar('GSTIN', { length: 50 }),
    PANNo: varchar('PANNo', { length: 50 }),
    Phone1: varchar('Phone1', { length: 50 }),
    Phone2: varchar('Phone2', { length: 50 }),
    state: varchar('state', { length: 100 }),
    Statecode: integer('Statecode'),
    EmailID1: varchar('EmailID1', { length: 255 }),
    EmailID2: varchar('EmailID2', { length: 255 }),
    Website: varchar('Website', { length: 255 }),
    VATno: integer('VATno'),
    CSTNo: integer('CSTNo'),
    ECCNo: varchar('ECCNo', { length: 100 }),
    IECCode: varchar('IECCode', { length: 100 }),
    SupplyFrom: varchar('SupplyFrom', { length: 255 }),
    FinancialYear: varchar('FinancialYear', { length: 100 }),
    StartDate: timestamp('StartDate'),
    EndDate: timestamp('EndDate'),
    SalesInvoiceStarts: varchar('SalesInvoiceStarts', { length: 100 }),
    ServiceInvoiceStarts: varchar('ServiceInvoiceStarts', { length: 100 }),
    ProformaSalesInvoiceStarts: varchar('ProformaSalesInvoiceStarts', { length: 100 }),
    ProformaServiceInvoiceStarts: varchar('ProformaServiceInvoiceStarts', { length: 100 }),
    SalesInvoicePrefix: varchar('SalesInvoicePrefix', { length: 50 }),
    ServiceInvoicePrefix: varchar('ServiceInvoicePrefix', { length: 50 }),
    ProformaSalesInvoicePrefix: varchar('ProformaSalesInvoicePrefix', { length: 50 }),
    ProformaServiceInvoicePrefix: varchar('ProformaServiceInvoicePrefix', { length: 50 }),
    QuotationStarts: varchar('QuotationStarts', { length: 100 }),
    QuotationPrefix: varchar('QuotationPrefix', { length: 50 }),
    ProposalStarts: varchar('ProposalStarts', { length: 100 }),
    ProposalPrefix: varchar('ProposalPrefix', { length: 50 }),
    ISOText: text('ISOText'),
    Loc: varchar('Loc', { length: 255 }),
    Pin: varchar('Pin', { length: 50 }),
    SignatureImage: varchar('SignatureImage', { length: 255 }),
    createdAt: timestamp('created_at').defaultNow(),
    updatedAt: timestamp('updated_at').$onUpdate(() => new Date()),
})

export const bankTable = pgTable('Bank', {
    BankID: integer('BankID').primaryKey().generatedAlwaysAsIdentity(),
    CompanyID: integer('CompanyID').references(() => companyTable.CompanyID),
    BankName: varchar('BankName', { length: 255 }),
    AccountNo: varchar('AccountNo', { length: 255 }),
    IFSCCode: varchar('IFSCCode', { length: 50 }),
    SwiftCode: varchar('SwiftCode', { length: 100 }),
    Company: varchar('Company', { length: 255 }),
    createdAt: timestamp('created_at').defaultNow(),
    updatedAt: timestamp('updated_at').$onUpdate(() => new Date()),
})

export const financialSettingsTable = pgTable('FinancialSettings', {
    FinancialYearID: integer('FinancialYearID').primaryKey().generatedAlwaysAsIdentity(),
    CompanyID: integer('CompanyID').notNull().references(() => companyTable.CompanyID, { onDelete: 'cascade' }),
    FinancialYear: varchar('FinancialYear', { length: 100 }).notNull(),
    StartDate: timestamp('StartDate').notNull(),
    EndDate: timestamp('EndDate').notNull(),
    SalesInvoiceCount: varchar('SalesInvoiceCount', { length: 100 }),
    ServiceInvoiceCount: varchar('ServiceInvoiceCount', { length: 100 }),
    ProformaSalesInvoiceCount: varchar('ProformaSalesInvoiceCount', { length: 100 }),
    ProformaServiceInvoiceCount: varchar('ProformaServiceInvoiceCount', { length: 100 }),
    QuotationCount: varchar('QuotationCount', { length: 100 }),
    ProposalCount: varchar('ProposalCount', { length: 100 }),
    createdAt: timestamp('created_at').defaultNow(),
    updatedAt: timestamp('updated_at').$onUpdate(() => new Date()),
})

export const companyRelations = relations(companyTable, ({ many }) => ({
    financialYears: many(financialSettingsTable),
}))

export const financialSettingsRelations = relations(financialSettingsTable, ({ one }) => ({
    company: one(companyTable, {
        fields: [financialSettingsTable.CompanyID],
        references: [companyTable.CompanyID],
    }),
}))

export const partyTable = pgTable('Party', {
    PartyID: integer('PartyID').primaryKey().generatedAlwaysAsIdentity(),
    PartyName: varchar('PartyName', { length: 255 }).notNull(),
    ContactPerson: varchar('ContactPerson', { length: 255 }),
    Contact1: varchar('Contact1', { length: 100 }),
    Contact2: varchar('Contact2', { length: 100 }),
    Address: text('Address'),
    City: varchar('City', { length: 100 }),
    State: varchar('State', { length: 100 }),
    Country: varchar('Country', { length: 100 }),
    StateCode: integer('StateCode'),
    Email: varchar('Email', { length: 255 }),
    Website: varchar('Website', { length: 255 }),
    GSTStatus: varchar('GSTStatus', { length: 100 }),
    GSTIN: varchar('GSTIN', { length: 50 }),
    PANNo: varchar('PANNo', { length: 50 }),
    VATNo: integer('VATNo'),
    CSTNo: integer('CSTNo'),
    ECCNo: varchar('ECCNo', { length: 100 }),
    IECCode: varchar('IECCode', { length: 100 }),
    Company: varchar('Company', { length: 255 }),
    Pin: varchar('Pin', { length: 50 }),
    createdAt: timestamp('created_at').defaultNow(),
    updatedAt: timestamp('updated_at').$onUpdate(() => new Date()),
})

export const vendorTable = pgTable('Vendor', {
    VendorID: integer('VendorID').primaryKey().generatedAlwaysAsIdentity(),
    VendorName: varchar('VendorName', { length: 255 }).notNull(),
    ContactPerson: varchar('ContactPerson', { length: 255 }),
    Contact1: varchar('Contact1', { length: 100 }),
    Contact2: varchar('Contact2', { length: 100 }),
    Address: text('Address'),
    City: varchar('City', { length: 100 }),
    State: varchar('State', { length: 100 }),
    StateCode: integer('StateCode'),
    Email: varchar('Email', { length: 255 }),
    Website: varchar('Website', { length: 255 }),
    GSTStatus: varchar('GSTStatus', { length: 100 }),
    GSTIN: varchar('GSTIN', { length: 50 }),
    PANNo: varchar('PANNo', { length: 50 }),
    VATNo: integer('VATNo'),
    CSTNo: integer('CSTNo'),
    ECCNo: varchar('ECCNo', { length: 100 }),
    IECCode: varchar('IECCode', { length: 100 }),
    Company: varchar('Company', { length: 255 }),
    createdAt: timestamp('created_at').defaultNow(),
    updatedAt: timestamp('updated_at').$onUpdate(() => new Date()),
})

export const categoryTable = pgTable('Category', {
    CategoryID: integer('CategoryID').primaryKey().generatedAlwaysAsIdentity(),
    CompanyID: integer('CompanyID').references(() => companyTable.CompanyID),
    CategoryName: varchar('CategoryName', { length: 255 }).notNull(),
    createdAt: timestamp('created_at').defaultNow(),
    updatedAt: timestamp('updated_at').$onUpdate(() => new Date()),
})

export const subCategoryTable = pgTable('SubCategory', {
    SubCategoryID: integer('SubCategoryID').primaryKey().generatedAlwaysAsIdentity(),
    CategoryID: integer('CategoryID').references(() => categoryTable.CategoryID),
    SubCategoryName: varchar('SubCategoryName', { length: 255 }).notNull(),
    Company: varchar('Company', { length: 255 }),
    createdAt: timestamp('created_at').defaultNow(),
    updatedAt: timestamp('updated_at').$onUpdate(() => new Date()),
})

export const productTable = pgTable('Product', {
    ProductID: integer('ProductID').primaryKey().generatedAlwaysAsIdentity(),
    CategoryID: integer('CategoryID').references(() => categoryTable.CategoryID),
    SubCategoryID: integer('SubCategoryID').references(() => subCategoryTable.SubCategoryID),
    ProductName: varchar('ProductName', { length: 255 }).notNull(),
    UOM: varchar('UOM', { length: 100 }),
    HSNNoOrSACNo: varchar('HSNNoOrSACNo', { length: 100 }),
    MachineNo: varchar('MachineNo', { length: 100 }),
    Price: decimal('Price', { precision: 15, scale: 2 }),
    FullProductName: varchar('FullProductName', { length: 255 }),
    IsService: boolean('IsService'),
    Company: varchar('Company', { length: 255 }),
    createdAt: timestamp('created_at').defaultNow(),
    updatedAt: timestamp('updated_at').$onUpdate(() => new Date()),
})

export const poProductTable = pgTable('POProduct', {
    POProductID: integer('POProductID').primaryKey().generatedAlwaysAsIdentity(),
    CategoryID: integer('CategoryID').references(() => categoryTable.CategoryID),
    SubCategoryID: integer('SubCategoryID').references(() => subCategoryTable.SubCategoryID),
    ProductName: varchar('ProductName', { length: 255 }).notNull(),
    UOM: varchar('UOM', { length: 100 }),
    HSNNoOrSACNo: varchar('HSNNoOrSACNo', { length: 100 }),
    MachineNo: varchar('MachineNo', { length: 100 }),
    Price: decimal('Price', { precision: 15, scale: 2 }),
    FullProductName: varchar('FullProductName', { length: 255 }),
    Company: varchar('Company', { length: 255 }),
    createdAt: timestamp('created_at').defaultNow(),
    updatedAt: timestamp('updated_at').$onUpdate(() => new Date()),
})

export const stockCategoryTable = pgTable('StockCategory', {
    StockCategoryID: integer('StockCategoryID').primaryKey().generatedAlwaysAsIdentity(),
    StockCategoryName: varchar('StockCategoryName', { length: 255 }).notNull(),
    Company: varchar('Company', { length: 255 }),
    createdAt: timestamp('created_at').defaultNow(),
    updatedAt: timestamp('updated_at').$onUpdate(() => new Date()),
})

export const stockSubCategoryTable = pgTable('StockSubCategory', {
    StockSubCategoryID: integer('StockSubCategoryID').primaryKey().generatedAlwaysAsIdentity(),
    StockCategoryID: integer('StockCategoryID').references(() => stockCategoryTable.StockCategoryID),
    StockSubCategoryName: varchar('StockSubCategoryName', { length: 255 }).notNull(),
    Company: varchar('Company', { length: 255 }),
    createdAt: timestamp('created_at').defaultNow(),
    updatedAt: timestamp('updated_at').$onUpdate(() => new Date()),
})

export const modelTable = pgTable('Model', {
    ModelID: integer('ModelID').primaryKey().generatedAlwaysAsIdentity(),
    ModelName: varchar('ModelName', { length: 255 }).notNull(),
    Company: varchar('Company', { length: 255 }),
    createdAt: timestamp('created_at').defaultNow(),
    updatedAt: timestamp('updated_at').$onUpdate(() => new Date()),
})

export const plungerDiaTable = pgTable('PlungerDia', {
    PlungerDiaID: integer('PlungerDiaID').primaryKey().generatedAlwaysAsIdentity(),
    PlungerDiaName: varchar('PlungerDiaName', { length: 255 }).notNull(),
    Company: varchar('Company', { length: 255 }),
    createdAt: timestamp('created_at').defaultNow(),
    updatedAt: timestamp('updated_at').$onUpdate(() => new Date()),
})

export const mocTable = pgTable('MOC', {
    MOCID: integer('MOCID').primaryKey().generatedAlwaysAsIdentity(),
    MOCName: varchar('MOCName', { length: 255 }).notNull(),
    Company: varchar('Company', { length: 255 }),
    createdAt: timestamp('created_at').defaultNow(),
    updatedAt: timestamp('updated_at').$onUpdate(() => new Date()),
})

export const typeTable = pgTable('Type', {
    TypeID: integer('TypeID').primaryKey().generatedAlwaysAsIdentity(),
    TypeName: varchar('TypeName', { length: 255 }).notNull(),
    Company: varchar('Company', { length: 255 }),
    createdAt: timestamp('created_at').defaultNow(),
    updatedAt: timestamp('updated_at').$onUpdate(() => new Date()),
})

export const stockProductTable = pgTable('StockProduct', {
    StockProductID: integer('StockProductID').primaryKey().generatedAlwaysAsIdentity(),
    StockCategoryID: integer('StockCategoryID').references(() => stockCategoryTable.StockCategoryID),
    StockSubCategoryID: integer('StockSubCategoryID').references(() => stockSubCategoryTable.StockSubCategoryID),
    ModelID: integer('ModelID').references(() => modelTable.ModelID),
    PlungerDiaID: integer('PlungerDiaID').references(() => plungerDiaTable.PlungerDiaID),
    MOCID: integer('MOCID').references(() => mocTable.MOCID),
    ProductName: varchar('ProductName', { length: 255 }).notNull(),
    Description: text('Description'),
    UOM: varchar('UOM', { length: 100 }),
    HSN: varchar('HSN', { length: 100 }),
    GSTRate: decimal('GSTRate', { precision: 5, scale: 2 }),
    PricePerUnit: decimal('PricePerUnit', { precision: 15, scale: 2 }),
    OpeningQTY: decimal('OpeningQTY', { precision: 15, scale: 4 }),
    ClosingQTY: decimal('ClosingQTY', { precision: 15, scale: 4 }),
    OpeningStockVal: decimal('OpeningStockVal', { precision: 15, scale: 2 }),
    ClosingStockVal: decimal('ClosingStockVal', { precision: 15, scale: 2 }),
    ReOrderLevel: decimal('ReOrderLevel', { precision: 15, scale: 4 }),
    FullGoodsName: varchar('FullGoodsName', { length: 255 }),
    LastUpdated: varchar('LastUpdated', { length: 255 }),
    Company: varchar('Company', { length: 255 }),
    createdAt: timestamp('created_at').defaultNow(),
    updatedAt: timestamp('updated_at').$onUpdate(() => new Date()),
})

export const proposalSignatoryTable = pgTable('ProposalSignatory', {
    SignatoryID: integer('SignatoryID').primaryKey().generatedAlwaysAsIdentity(),
    SignatoryName: varchar('SignatoryName', { length: 255 }).notNull(),
    MobileNo: varchar('MobileNo', { length: 100 }),
    CompanyName: varchar('CompanyName', { length: 255 }),
    CompanyID: integer('CompanyID').references(() => companyTable.CompanyID),
    createdAt: timestamp('created_at').defaultNow(),
    updatedAt: timestamp('updated_at').$onUpdate(() => new Date()),
})

export const goodsTable = pgTable('Goods', {
    GoodsID: integer('GoodsID').primaryKey().generatedAlwaysAsIdentity(),
    TypeID: integer('TypeID').references(() => typeTable.TypeID),
    TypeName: varchar('TypeName', { length: 255 }),
    StockCategoryID: integer('StockCategoryID').references(() => stockCategoryTable.StockCategoryID),
    StockSubCategoryID: integer('StockSubCategoryID').references(() => stockSubCategoryTable.StockSubCategoryID),
    ModelName: varchar('ModelName', { length: 255 }),
    PlungerDiaName: varchar('PlungerDiaName', { length: 255 }),
    GoodsName: varchar('GoodsName', { length: 255 }),
    Description: text('Description'),
    UOM: varchar('UOM', { length: 100 }),
    HSN: varchar('HSN', { length: 100 }),
    GSTRate: decimal('GSTRate', { precision: 5, scale: 2 }),
    AvgPricePerUnit: decimal('AvgPricePerUnit', { precision: 15, scale: 2 }),
    OpeningQTY: decimal('OpeningQTY', { precision: 15, scale: 4 }),
    ClosingQTY: decimal('ClosingQTY', { precision: 15, scale: 4 }),
    ClosingStockVal: decimal('ClosingStockVal', { precision: 15, scale: 2 }),
    ReOrderLevel: decimal('ReOrderLevel', { precision: 15, scale: 4 }),
    FullGoodsName: varchar('FullGoodsName', { length: 255 }),
    LastUpdate: varchar('LastUpdate', { length: 255 }),
    Company: varchar('Company', { length: 255 }),
    CreatedAt: timestamp('CreatedAt').defaultNow(),
    UpdatedAt: timestamp('UpdatedAt').$onUpdate(() => new Date()),
})

export const goodsInventoryTable = pgTable('GoodsInventory', {
    InventoryID: bigint('InventoryID', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
    GoodsID: integer('GoodsID').references(() => goodsTable.GoodsID),
    PartyName: varchar('PartyName', { length: 255 }),
    PartyOtherdetail: varchar('PartyOtherdetail', { length: 255 }),
    InvDate: timestamp('InvDate'),
    UMO: varchar('UMO', { length: 100 }),
    Qty: decimal('Qty', { precision: 15, scale: 4 }),
    PricePerUnit: decimal('PricePerUnit', { precision: 15, scale: 2 }),
    TotalPrice: decimal('TotalPrice', { precision: 15, scale: 2 }),
    Remarks: text('Remarks'),
    InventoryType: varchar('InventoryType', { length: 100 }),
    Company: varchar('Company', { length: 255 }),
    CreatedAt: timestamp('CreatedAt').defaultNow(),
    UpdatedAt: timestamp('UpdatedAt').$onUpdate(() => new Date()),
})

export const invoiceTable = pgTable('Invoice', {
    InvoiceID: integer('InvoiceID').primaryKey().generatedAlwaysAsIdentity(),
    InvoiceNo: text('InvoiceNo'),
    InvoiceDate: timestamp('InvoiceDate'),
    PartyID: integer('PartyID').references(() => partyTable.PartyID),
    ChallanNo: varchar('ChallanNo', { length: 255 }),
    ChallanDate: timestamp('ChallanDate'),
    PartyDCNo: varchar('PartyDCNo', { length: 255 }),
    PartyDCDate: timestamp('PartyDCDate'),
    PO: varchar('PO', { length: 255 }),
    PODate: timestamp('PODate'),
    ARNNo: varchar('ARNNo', { length: 255 }),
    ARNDate: timestamp('ARNDate'),
    TransportationMode: varchar('TransportationMode', { length: 255 }),
    SupplyTo: varchar('SupplyTo', { length: 255 }),
    SupplyStateCode: integer('SupplyStateCode'),
    ModelNo: varchar('ModelNo', { length: 255 }),
    AgainstForm: varchar('AgainstForm', { length: 255 }),
    ReceiverName: varchar('ReceiverName', { length: 255 }),
    ReceiverAddress: text('ReceiverAddress'),
    ReceiverGSTIN: varchar('ReceiverGSTIN', { length: 100 }),
    ReceiverState: varchar('ReceiverState', { length: 100 }),
    ReceiverStateCode: varchar('ReceiverStateCode', { length: 100 }),
    ReceiverPanNo: varchar('ReceiverPanNo', { length: 100 }),
    ConsigneeName: varchar('ConsigneeName', { length: 255 }),
    ConsigneePartyID: integer('ConsigneePartyID').references(() => partyTable.PartyID),
    ConsigneeAddress: text('ConsigneeAddress'),
    ConsigneeGSTIN: varchar('ConsigneeGSTIN', { length: 100 }),
    ConsigneeState: varchar('ConsigneeState', { length: 100 }),
    ConsigneeStateCode: varchar('ConsigneeStateCode', { length: 100 }),
    ConsigneePanNo: varchar('ConsigneePanNo', { length: 100 }),
    IsSameAddress: boolean('IsSameAddress'),
    TotalAmtBeforeTax: decimal('TotalAmtBeforeTax', { precision: 15, scale: 2 }),
    PackingCharge: decimal('PackingCharge', { precision: 15, scale: 2 }),
    PCGSTRate: decimal('PCGSTRate', { precision: 5, scale: 2 }),
    PCGSTAmt: decimal('PCGSTAmt', { precision: 15, scale: 2 }),
    PSGSTRate: decimal('PSGSTRate', { precision: 5, scale: 2 }),
    PSGSTAmt: decimal('PSGSTAmt', { precision: 15, scale: 2 }),
    PIGSTRate: decimal('PIGSTRate', { precision: 5, scale: 2 }),
    PIGSTAmt: decimal('PIGSTAmt', { precision: 15, scale: 2 }),
    CGST: decimal('CGST', { precision: 15, scale: 2 }),
    SGST: decimal('SGST', { precision: 15, scale: 2 }),
    IGST: decimal('IGST', { precision: 15, scale: 2 }),
    TotalGSTTax: decimal('TotalGSTTax', { precision: 15, scale: 2 }),
    TotalAmtAfterTax: decimal('TotalAmtAfterTax', { precision: 15, scale: 2 }),
    GSTReverseCharge: decimal('GSTReverseCharge', { precision: 15, scale: 2 }),
    TotalInWords: text('TotalInWords'),
    TaxInWords: text('TaxInWords'),
    Remarks: text('Remarks'),
    GrandTotalAmount: decimal('GrandTotalAmount', { precision: 15, scale: 2 }),
    RoundOff: decimal('RoundOff', { precision: 15, scale: 2 }),
    CreatedBy: varchar('CreatedBy', { length: 255 }),
    ModifiedBy: varchar('ModifiedBy', { length: 255 }),
    CreatedAt: timestamp('CreatedAt').defaultNow(),
    UpdatedAt: timestamp('UpdatedAt').$onUpdate(() => new Date()),
    Company: varchar('Company', { length: 255 }),
    InvoiceType: varchar('InvoiceType', { length: 100 }),
    QRCode: text('QRCode'),
    IRNNo: varchar('IRNNo', { length: 255 }),
    AckNo: varchar('AckNo', { length: 255 }),
    AckDate: varchar('AckDate', { length: 255 }),
    TransId: varchar('TransId', { length: 255 }),
    TransName: varchar('TransName', { length: 255 }),
    TransMode: varchar('TransMode', { length: 255 }),
    Distance: varchar('Distance', { length: 255 }),
    VehNo: varchar('VehNo', { length: 255 }),
    VehType: varchar('VehType', { length: 255 }),
    EwbNo: varchar('EwbNo', { length: 255 }),
    EwbDt: varchar('EwbDt', { length: 255 }),
    EwbValidTill: varchar('EwbValidTill', { length: 255 }),
    CEWBNo: varchar('CEWBNo', { length: 255 }),
    MultiVehInfo: varchar('MultiVehInfo', { length: 255 }),
    PlaceOfDel: varchar('PlaceOfDel', { length: 255 }),
    ShipPin: varchar('ShipPin', { length: 255 }),
})

export const invoiceDetailTable = pgTable('InvoiceDetail', {
    InvoiceDetailID: integer('InvoiceDetailID').primaryKey().generatedAlwaysAsIdentity(),
    InvoiceID: integer('InvoiceID').references(() => invoiceTable.InvoiceID),
    ProductName: varchar('ProductName', { length: 255 }),
    Description: text('Description'),
    HSNACS: varchar('HSNACS', { length: 100 }),
    UOM: varchar('UOM', { length: 100 }),
    Qty: decimal('Qty', { precision: 15, scale: 4 }),
    Rate: decimal('Rate', { precision: 15, scale: 2 }),
    IsService: varchar('IsService', { length: 50 }),
    Amount: decimal('Amount', { precision: 15, scale: 2 }),
    Discount: decimal('Discount', { precision: 15, scale: 2 }),
    DiscountVal: decimal('DiscountVal', { precision: 15, scale: 2 }),
    TaxableValue: decimal('TaxableValue', { precision: 15, scale: 2 }),
    CGSTRate: decimal('CGSTRate', { precision: 5, scale: 2 }),
    CGSTAmt: decimal('CGSTAmt', { precision: 15, scale: 2 }),
    SGSTRate: decimal('SGSTRate', { precision: 5, scale: 2 }),
    SGSTAmt: decimal('SGSTAmt', { precision: 15, scale: 2 }),
    IGSTRate: decimal('IGSTRate', { precision: 5, scale: 2 }),
    IGSTAmt: decimal('IGSTAmt', { precision: 15, scale: 2 }),
    TotalAmount: decimal('TotalAmount', { precision: 15, scale: 2 }),
    createdAt: timestamp('created_at').defaultNow(),
    updatedAt: timestamp('updated_at').$onUpdate(() => new Date()),
})

export const serviceInvoiceTable = pgTable('ServiceInvoice', {
    ServiceInvoiceID: integer('ServiceInvoiceID').primaryKey().generatedAlwaysAsIdentity(),
    InvoiceNo: text('InvoiceNo'),
    InvoiceDate: timestamp('InvoiceDate'),
    PartyID: integer('PartyID').references(() => partyTable.PartyID),
    ChallanNo: varchar('ChallanNo', { length: 255 }),
    ChallanDate: timestamp('ChallanDate'),
    PartyDCNo: varchar('PartyDCNo', { length: 255 }),
    PartyDCDate: timestamp('PartyDCDate'),
    PO: varchar('PO', { length: 255 }),
    PODate: timestamp('PODate'),
    ARNNo: varchar('ARNNo', { length: 255 }),
    ARNDate: timestamp('ARNDate'),
    TransportationMode: varchar('TransportationMode', { length: 255 }),
    SupplyTo: varchar('SupplyTo', { length: 255 }),
    SupplyStateCode: integer('SupplyStateCode'),
    AgainstForm: varchar('AgainstForm', { length: 255 }),
    ReceiverName: varchar('ReceiverName', { length: 255 }),
    ReceiverAddress: text('ReceiverAddress'),
    ReceiverGSTIN: varchar('ReceiverGSTIN', { length: 100 }),
    ReceiverState: varchar('ReceiverState', { length: 100 }),
    ReceiverStateCode: varchar('ReceiverStateCode', { length: 100 }),
    ReceiverPanNo: varchar('ReceiverPanNo', { length: 100 }),
    ConsigneeName: varchar('ConsigneeName', { length: 255 }),
    ConsigneePartyID: integer('ConsigneePartyID').references(() => partyTable.PartyID),
    ConsigneeAddress: text('ConsigneeAddress'),
    ConsigneeGSTIN: varchar('ConsigneeGSTIN', { length: 100 }),
    ConsigneeState: varchar('ConsigneeState', { length: 100 }),
    ConsigneeStateCode: varchar('ConsigneeStateCode', { length: 100 }),
    ConsigneePanNo: varchar('ConsigneePanNo', { length: 100 }),
    IsSameAddress: boolean('IsSameAddress'),
    TotalAmtBeforeTax: decimal('TotalAmtBeforeTax', { precision: 15, scale: 2 }),
    PackingCharge: decimal('PackingCharge', { precision: 15, scale: 2 }),
    PCGSTRate: decimal('PCGSTRate', { precision: 5, scale: 2 }),
    PCGSTAmt: decimal('PCGSTAmt', { precision: 15, scale: 2 }),
    PSGSTRate: decimal('PSGSTRate', { precision: 5, scale: 2 }),
    PSGSTAmt: decimal('PSGSTAmt', { precision: 15, scale: 2 }),
    PIGSTRate: decimal('PIGSTRate', { precision: 5, scale: 2 }),
    PIGSTAmt: decimal('PIGSTAmt', { precision: 15, scale: 2 }),
    CGST: decimal('CGST', { precision: 15, scale: 2 }),
    SGST: decimal('SGST', { precision: 15, scale: 2 }),
    IGST: decimal('IGST', { precision: 15, scale: 2 }),
    TotalGSTTax: decimal('TotalGSTTax', { precision: 15, scale: 2 }),
    TotalAmtAfterTax: decimal('TotalAmtAfterTax', { precision: 15, scale: 2 }),
    GSTReverseCharge: decimal('GSTReverseCharge', { precision: 15, scale: 2 }),
    TotalInWords: text('TotalInWords'),
    TaxInWords: text('TaxInWords'),
    Remarks: text('Remarks'),
    GrandTotalAmount: decimal('GrandTotalAmount', { precision: 15, scale: 2 }),
    RoundOff: decimal('RoundOff', { precision: 15, scale: 2 }),
    CreatedBy: varchar('CreatedBy', { length: 255 }),
    ModifiedBy: varchar('ModifiedBy', { length: 255 }),
    CreatedAt: timestamp('CreatedAt').defaultNow(),
    UpdatedAt: timestamp('UpdatedAt').$onUpdate(() => new Date()),
    Company: varchar('Company', { length: 255 }),
    InvoiceType: varchar('InvoiceType', { length: 100 }),
    QRCode: text('QRCode'),
    IRNNo: varchar('IRNNo', { length: 255 }),
    AckNo: varchar('AckNo', { length: 255 }),
    AckDate: varchar('AckDate', { length: 255 }),
})

export const serviceInvoiceDetailTable = pgTable('ServiceInvoiceDetail', {
    ServiceInvoiceDetailID: integer('ServiceInvoiceDetailID').primaryKey().generatedAlwaysAsIdentity(),
    ServiceInvoiceID: integer('ServiceInvoiceID').references(() => serviceInvoiceTable.ServiceInvoiceID),
    ProductName: varchar('ProductName', { length: 255 }),
    Description: text('Description'),
    HSNACS: varchar('HSNACS', { length: 100 }),
    UOM: varchar('UOM', { length: 100 }),
    Qty: decimal('Qty', { precision: 15, scale: 4 }),
    Rate: decimal('Rate', { precision: 15, scale: 2 }),
    IsService: varchar('IsService', { length: 50 }),
    Amount: decimal('Amount', { precision: 15, scale: 2 }),
    Discount: decimal('Discount', { precision: 15, scale: 2 }),
    DiscountVal: decimal('DiscountVal', { precision: 15, scale: 2 }),
    TaxableValue: decimal('TaxableValue', { precision: 15, scale: 2 }),
    CGSTRate: decimal('CGSTRate', { precision: 5, scale: 2 }),
    CGSTAmt: decimal('CGSTAmt', { precision: 15, scale: 2 }),
    SGSTRate: decimal('SGSTRate', { precision: 5, scale: 2 }),
    SGSTAmt: decimal('SGSTAmt', { precision: 15, scale: 2 }),
    IGSTRate: decimal('IGSTRate', { precision: 5, scale: 2 }),
    IGSTAmt: decimal('IGSTAmt', { precision: 15, scale: 2 }),
    TotalAmount: decimal('TotalAmount', { precision: 15, scale: 2 }),
    createdAt: timestamp('created_at').defaultNow(),
    updatedAt: timestamp('updated_at').$onUpdate(() => new Date()),
})

export const proformaInvoiceTable = pgTable('ProformaInvoice', {
    ProformaInvoiceID: integer('ProformaInvoiceID').primaryKey().generatedAlwaysAsIdentity(),
    InvoiceNo: varchar('InvoiceNo', { length: 255 }),
    InvoiceDate: timestamp('InvoiceDate'),
    PartyID: integer('PartyID').references(() => partyTable.PartyID),
    PartyDCNo: varchar('PartyDCNo', { length: 255 }),
    PartyDCDate: timestamp('PartyDCDate'),
    PO: varchar('PO', { length: 255 }),
    PODate: timestamp('PODate'),
    TransportationMode: varchar('TransportationMode', { length: 255 }),
    SupplyTo: varchar('SupplyTo', { length: 255 }),
    AgainstForm: varchar('AgainstForm', { length: 255 }),
    Packing: varchar('Packing', { length: 255 }),
    ReceiverName: varchar('ReceiverName', { length: 255 }),
    ReceiverAddress: text('ReceiverAddress'),
    ReceiverGSTIN: varchar('ReceiverGSTIN', { length: 100 }),
    ReceiverState: varchar('ReceiverState', { length: 100 }),
    ReceiverStateCode: varchar('ReceiverStateCode', { length: 100 }),
    ReceiverPanNo: varchar('ReceiverPanNo', { length: 100 }),
    ConsigneeName: varchar('ConsigneeName', { length: 255 }),
    ConsigneePartyID: integer('ConsigneePartyID').references(() => partyTable.PartyID),
    ConsigneeAddress: text('ConsigneeAddress'),
    ConsigneeGSTIN: varchar('ConsigneeGSTIN', { length: 100 }),
    ConsigneeState: varchar('ConsigneeState', { length: 100 }),
    ConsigneeStateCode: varchar('ConsigneeStateCode', { length: 100 }),
    ConsigneePanNo: varchar('ConsigneePanNo', { length: 100 }),
    IsSameAddress: boolean('IsSameAddress'),
    TotalAmtBeforeTax: decimal('TotalAmtBeforeTax', { precision: 15, scale: 2 }),
    PackingCharge: decimal('PackingCharge', { precision: 15, scale: 2 }),
    PCGSTRate: decimal('PCGSTRate', { precision: 5, scale: 2 }),
    PCGSTAmt: decimal('PCGSTAmt', { precision: 15, scale: 2 }),
    PSGSTRate: decimal('PSGSTRate', { precision: 5, scale: 2 }),
    PSGSTAmt: decimal('PSGSTAmt', { precision: 15, scale: 2 }),
    PIGSTRate: decimal('PIGSTRate', { precision: 5, scale: 2 }),
    PIGSTAmt: decimal('PIGSTAmt', { precision: 15, scale: 2 }),
    CGST: decimal('CGST', { precision: 15, scale: 2 }),
    SGST: decimal('SGST', { precision: 15, scale: 2 }),
    IGST: decimal('IGST', { precision: 15, scale: 2 }),
    TotalGSTTax: decimal('TotalGSTTax', { precision: 15, scale: 2 }),
    TotalAmtAfterTax: decimal('TotalAmtAfterTax', { precision: 15, scale: 2 }),
    GSTReverseCharge: decimal('GSTReverseCharge', { precision: 15, scale: 2 }),
    TotalInWords: text('TotalInWords'),
    TaxInWords: text('TaxInWords'),
    Remarks: text('Remarks'),
    GrandTotalAmount: decimal('GrandTotalAmount', { precision: 15, scale: 2 }),
    RoundOff: decimal('RoundOff', { precision: 15, scale: 2 }),
    CreatedBy: varchar('CreatedBy', { length: 255 }),
    ModifiedBy: varchar('ModifiedBy', { length: 255 }),
    CreatedAt: timestamp('CreatedAt').defaultNow(),
    UpdatedAt: timestamp('UpdatedAt').$onUpdate(() => new Date()),
    Company: varchar('Company', { length: 255 }),
    InvoiceType: varchar('InvoiceType', { length: 100 }),
})

export const proformaInvoiceDetailTable = pgTable('ProformaInvoiceDetail', {
    ProformaInvoiceDetailID: integer('ProformaInvoiceDetailID').primaryKey().generatedAlwaysAsIdentity(),
    ProformaInvoiceID: integer('ProformaInvoiceID').references(() => proformaInvoiceTable.ProformaInvoiceID),
    ProductName: varchar('ProductName', { length: 255 }),
    Description: text('Description'),
    HSNACS: varchar('HSNACS', { length: 100 }),
    UOM: varchar('UOM', { length: 100 }),
    Qty: decimal('Qty', { precision: 15, scale: 4 }),
    Rate: decimal('Rate', { precision: 15, scale: 2 }),
    Amount: decimal('Amount', { precision: 15, scale: 2 }),
    Discount: decimal('Discount', { precision: 15, scale: 2 }),
    DiscountVal: decimal('DiscountVal', { precision: 15, scale: 2 }),
    TaxableValue: decimal('TaxableValue', { precision: 15, scale: 2 }),
    CGSTRate: decimal('CGSTRate', { precision: 5, scale: 2 }),
    CGSTAmt: decimal('CGSTAmt', { precision: 15, scale: 2 }),
    SGSTRate: decimal('SGSTRate', { precision: 5, scale: 2 }),
    SGSTAmt: decimal('SGSTAmt', { precision: 15, scale: 2 }),
    IGSTRate: decimal('IGSTRate', { precision: 5, scale: 2 }),
    IGSTAmt: decimal('IGSTAmt', { precision: 15, scale: 2 }),
    TotalAmount: decimal('TotalAmount', { precision: 15, scale: 2 }),
    createdAt: timestamp('created_at').defaultNow(),
    updatedAt: timestamp('updated_at').$onUpdate(() => new Date()),
})

export const proformaServiceInvoiceTable = pgTable('ProformaServiceInvoice', {
    ProformaServiceInvoiceID: integer('ProformaServiceInvoiceID').primaryKey().generatedAlwaysAsIdentity(),
    InvoiceNo: varchar('InvoiceNo', { length: 255 }),
    InvoiceDate: timestamp('InvoiceDate'),
    PartyID: integer('PartyID').references(() => partyTable.PartyID),
    PartyDCNo: varchar('PartyDCNo', { length: 255 }),
    PartyDCDate: timestamp('PartyDCDate'),
    PO: varchar('PO', { length: 255 }),
    PODate: timestamp('PODate'),
    TransportationMode: varchar('TransportationMode', { length: 255 }),
    SupplyTo: varchar('SupplyTo', { length: 255 }),
    AgainstForm: varchar('AgainstForm', { length: 255 }),
    Packing: varchar('Packing', { length: 255 }),
    ReceiverName: varchar('ReceiverName', { length: 255 }),
    ReceiverAddress: text('ReceiverAddress'),
    ReceiverGSTIN: varchar('ReceiverGSTIN', { length: 100 }),
    ReceiverState: varchar('ReceiverState', { length: 100 }),
    ReceiverStateCode: varchar('ReceiverStateCode', { length: 100 }),
    ReceiverPanNo: varchar('ReceiverPanNo', { length: 100 }),
    ConsigneeName: varchar('ConsigneeName', { length: 255 }),
    ConsigneePartyID: integer('ConsigneePartyID').references(() => partyTable.PartyID),
    ConsigneeAddress: varchar('ConsigneeAddress', { length: 255 }),
    ConsigneeGSTIN: varchar('ConsigneeGSTIN', { length: 100 }),
    ConsigneeState: varchar('ConsigneeState', { length: 100 }),
    ConsigneeStateCode: varchar('ConsigneeStateCode', { length: 100 }),
    ConsigneePanNo: varchar('ConsigneePanNo', { length: 100 }),
    IsSameAddress: boolean('IsSameAddress'),
    TotalAmtBeforeTax: decimal('TotalAmtBeforeTax', { precision: 15, scale: 2 }),
    PackingCharge: decimal('PackingCharge', { precision: 15, scale: 2 }),
    PCGSTRate: decimal('PCGSTRate', { precision: 5, scale: 2 }),
    PCGSTAmt: decimal('PCGSTAmt', { precision: 15, scale: 2 }),
    PSGSTRate: decimal('PSGSTRate', { precision: 5, scale: 2 }),
    PSGSTAmt: decimal('PSGSTAmt', { precision: 15, scale: 2 }),
    PIGSTRate: decimal('PIGSTRate', { precision: 5, scale: 2 }),
    PIGSTAmt: decimal('PIGSTAmt', { precision: 15, scale: 2 }),
    CGST: decimal('CGST', { precision: 15, scale: 2 }),
    SGST: decimal('SGST', { precision: 15, scale: 2 }),
    IGST: decimal('IGST', { precision: 15, scale: 2 }),
    TotalGSTTax: decimal('TotalGSTTax', { precision: 15, scale: 2 }),
    TotalAmtAfterTax: decimal('TotalAmtAfterTax', { precision: 15, scale: 2 }),
    GSTReverseCharge: decimal('GSTReverseCharge', { precision: 15, scale: 2 }),
    TotalInWords: text('TotalInWords'),
    TaxInWords: text('TaxInWords'),
    Remarks: text('Remarks'),
    GrandTotalAmount: decimal('GrandTotalAmount', { precision: 15, scale: 2 }),
    RoundOff: decimal('RoundOff', { precision: 15, scale: 2 }),
    CreatedBy: varchar('CreatedBy', { length: 255 }),
    ModifiedBy: varchar('ModifiedBy', { length: 255 }),
    CreatedAt: timestamp('CreatedAt').defaultNow(),
    UpdatedAt: timestamp('UpdatedAt').$onUpdate(() => new Date()),
    Company: varchar('Company', { length: 255 }),
    InvoiceType: varchar('InvoiceType', { length: 100 }),
})

export const proformaServiceInvoiceDetailTable = pgTable('ProformaServiceInvoiceDetail', {
    ProformaServiceInvoiceDetailID: integer('ProformaServiceInvoiceDetailID').primaryKey().generatedAlwaysAsIdentity(),
    ProformaServiceInvoiceID: integer('ProformaServiceInvoiceID').references(() => proformaServiceInvoiceTable.ProformaServiceInvoiceID),
    ProductName: varchar('ProductName', { length: 255 }),
    Description: text('Description'),
    HSNACS: varchar('HSNACS', { length: 100 }),
    UOM: varchar('UOM', { length: 100 }),
    Qty: decimal('Qty', { precision: 15, scale: 4 }),
    Rate: decimal('Rate', { precision: 15, scale: 2 }),
    Amount: decimal('Amount', { precision: 15, scale: 2 }),
    Discount: decimal('Discount', { precision: 15, scale: 2 }),
    DiscountVal: decimal('DiscountVal', { precision: 15, scale: 2 }),
    TaxableValue: decimal('TaxableValue', { precision: 15, scale: 2 }),
    CGSTRate: decimal('CGSTRate', { precision: 5, scale: 2 }),
    CGSTAmt: decimal('CGSTAmt', { precision: 15, scale: 2 }),
    SGSTRate: decimal('SGSTRate', { precision: 5, scale: 2 }),
    SGSTAmt: decimal('SGSTAmt', { precision: 15, scale: 2 }),
    IGSTRate: decimal('IGSTRate', { precision: 5, scale: 2 }),
    IGSTAmt: decimal('IGSTAmt', { precision: 15, scale: 2 }),
    TotalAmount: decimal('TotalAmount', { precision: 15, scale: 2 }),
    createdAt: timestamp('created_at').defaultNow(),
    updatedAt: timestamp('updated_at').$onUpdate(() => new Date()),
})

export const purchaseOrderTable = pgTable('PurchaseOrder', {
    PurchaseOrderID: integer('PurchaseOrderID').primaryKey().generatedAlwaysAsIdentity(),
    PO: varchar('PO', { length: 255 }),
    PODate: timestamp('PODate'),
    VendorID: integer('VendorID').references(() => vendorTable.VendorID),
    DeliverySchedule: varchar('DeliverySchedule', { length: 255 }),
    QuotRef: varchar('QuotRef', { length: 255 }),
    TransportorFOR: varchar('TransportorFOR', { length: 255 }),
    PaymentDays: varchar('PaymentDays', { length: 255 }),
    AgainstForm: varchar('AgainstForm', { length: 255 }),
    ConsignorName: varchar('ConsignorName', { length: 255 }),
    ConsignorAddress: text('ConsignorAddress'),
    ConsignorGSTIN: varchar('ConsignorGSTIN', { length: 100 }),
    ConsignorState: varchar('ConsignorState', { length: 100 }),
    ConsignorStateCode: varchar('ConsignorStateCode', { length: 100 }),
    ConsignorPanNo: varchar('ConsignorPanNo', { length: 100 }),
    TotalAmtBeforeTax: decimal('TotalAmtBeforeTax', { precision: 15, scale: 2 }),
    CGST: decimal('CGST', { precision: 15, scale: 2 }),
    SGST: decimal('SGST', { precision: 15, scale: 2 }),
    IGST: decimal('IGST', { precision: 15, scale: 2 }),
    TotalGSTTax: decimal('TotalGSTTax', { precision: 15, scale: 2 }),
    TotalAmtAfterTax: decimal('TotalAmtAfterTax', { precision: 15, scale: 2 }),
    GSTReverseCharge: decimal('GSTReverseCharge', { precision: 15, scale: 2 }),
    TotalInWords: text('TotalInWords'),
    TaxInWords: text('TaxInWords'),
    Remarks: text('Remarks'),
    GrandTotalAmount: decimal('GrandTotalAmount', { precision: 15, scale: 2 }),
    RoundOff: decimal('RoundOff', { precision: 15, scale: 2 }),
    CreatedBy: varchar('CreatedBy', { length: 255 }),
    ModifiedBy: varchar('ModifiedBy', { length: 255 }),
    CreatedAt: timestamp('CreatedAt').defaultNow(),
    UpdatedAt: timestamp('UpdatedAt').$onUpdate(() => new Date()),
    Company: varchar('Company', { length: 255 }),
    POType: varchar('POType', { length: 100 }),
})

export const purchaseOrderDetailTable = pgTable('PurchaseOrderDetail', {
    PurchaseOrderDetailID: integer('PurchaseOrderDetailID').primaryKey().generatedAlwaysAsIdentity(),
    PurchaseOrderID: integer('PurchaseOrderID').references(() => purchaseOrderTable.PurchaseOrderID),
    ProductName: varchar('ProductName', { length: 255 }),
    Description: text('Description'),
    HSNACS: varchar('HSNACS', { length: 100 }),
    UOM: varchar('UOM', { length: 100 }),
    Qty: decimal('Qty', { precision: 15, scale: 4 }),
    Rate: decimal('Rate', { precision: 15, scale: 2 }),
    Amount: decimal('Amount', { precision: 15, scale: 2 }),
    Discount: decimal('Discount', { precision: 15, scale: 2 }),
    DiscountVal: decimal('DiscountVal', { precision: 15, scale: 2 }),
    TaxableValue: decimal('TaxableValue', { precision: 15, scale: 2 }),
    CGSTRate: decimal('CGSTRate', { precision: 5, scale: 2 }),
    CGSTAmt: decimal('CGSTAmt', { precision: 15, scale: 2 }),
    SGSTRate: decimal('SGSTRate', { precision: 5, scale: 2 }),
    SGSTAmt: decimal('SGSTAmt', { precision: 15, scale: 2 }),
    IGSTRate: decimal('IGSTRate', { precision: 5, scale: 2 }),
    IGSTAmt: decimal('IGSTAmt', { precision: 15, scale: 2 }),
    TotalAmount: decimal('TotalAmount', { precision: 15, scale: 2 }),
    createdAt: timestamp('created_at').defaultNow(),
    updatedAt: timestamp('updated_at').$onUpdate(() => new Date()),
})

export const workOrderTable = pgTable('WorkOrder', {
    WorkOrderID: integer('WorkOrderID').primaryKey().generatedAlwaysAsIdentity(),
    WO: varchar('WO', { length: 255 }),
    WODate: timestamp('WODate'),
    VendorID: integer('VendorID').references(() => vendorTable.VendorID),
    DeliverySchedule: varchar('DeliverySchedule', { length: 255 }),
    QuotRef: varchar('QuotRef', { length: 255 }),
    TransportorFOR: varchar('TransportorFOR', { length: 255 }),
    PaymentDays: varchar('PaymentDays', { length: 255 }),
    AgainstForm: varchar('AgainstForm', { length: 255 }),
    ConsignorName: varchar('ConsignorName', { length: 255 }),
    ConsignorAddress: text('ConsignorAddress'),
    ConsignorGSTIN: varchar('ConsignorGSTIN', { length: 100 }),
    ConsignorState: varchar('ConsignorState', { length: 100 }),
    ConsignorStateCode: varchar('ConsignorStateCode', { length: 100 }),
    ConsignorPanNo: varchar('ConsignorPanNo', { length: 100 }),
    TotalAmtBeforeTax: decimal('TotalAmtBeforeTax', { precision: 15, scale: 2 }),
    CGST: decimal('CGST', { precision: 15, scale: 2 }),
    SGST: decimal('SGST', { precision: 15, scale: 2 }),
    IGST: decimal('IGST', { precision: 15, scale: 2 }),
    TotalGSTTax: decimal('TotalGSTTax', { precision: 15, scale: 2 }),
    TotalAmtAfterTax: decimal('TotalAmtAfterTax', { precision: 15, scale: 2 }),
    GSTReverseCharge: decimal('GSTReverseCharge', { precision: 15, scale: 2 }),
    TotalInWords: text('TotalInWords'),
    TaxInWords: text('TaxInWords'),
    Remarks: text('Remarks'),
    GrandTotalAmount: decimal('GrandTotalAmount', { precision: 15, scale: 2 }),
    RoundOff: decimal('RoundOff', { precision: 15, scale: 2 }),
    CreatedBy: varchar('CreatedBy', { length: 255 }),
    ModifiedBy: varchar('ModifiedBy', { length: 255 }),
    CreatedAt: timestamp('CreatedAt').defaultNow(),
    UpdatedAt: timestamp('UpdatedAt').$onUpdate(() => new Date()),
    Company: varchar('Company', { length: 255 }),
    WOType: varchar('WOType', { length: 100 }),
})

export const workOrderDetailTable = pgTable('WorkOrderDetail', {
    WorkOrderDetailID: integer('WorkOrderDetailID').primaryKey().generatedAlwaysAsIdentity(),
    WorkOrderID: integer('WorkOrderID').references(() => workOrderTable.WorkOrderID),
    ProductName: varchar('ProductName', { length: 255 }),
    Description: text('Description'),
    HSNACS: varchar('HSNACS', { length: 100 }),
    UOM: varchar('UOM', { length: 100 }),
    Qty: decimal('Qty', { precision: 15, scale: 4 }),
    Rate: decimal('Rate', { precision: 15, scale: 2 }),
    Amount: decimal('Amount', { precision: 15, scale: 2 }),
    Discount: decimal('Discount', { precision: 15, scale: 2 }),
    DiscountVal: decimal('DiscountVal', { precision: 15, scale: 2 }),
    TaxableValue: decimal('TaxableValue', { precision: 15, scale: 2 }),
    CGSTRate: decimal('CGSTRate', { precision: 5, scale: 2 }),
    CGSTAmt: decimal('CGSTAmt', { precision: 15, scale: 2 }),
    SGSTRate: decimal('SGSTRate', { precision: 5, scale: 2 }),
    SGSTAmt: decimal('SGSTAmt', { precision: 15, scale: 2 }),
    IGSTRate: decimal('IGSTRate', { precision: 5, scale: 2 }),
    IGSTAmt: decimal('IGSTAmt', { precision: 15, scale: 2 }),
    TotalAmount: decimal('TotalAmount', { precision: 15, scale: 2 }),
    createdAt: timestamp('created_at').defaultNow(),
    updatedAt: timestamp('updated_at').$onUpdate(() => new Date()),
})

export const quotationTable = pgTable('Quotation', {
    QuotationID: integer('QuotationID').primaryKey().generatedAlwaysAsIdentity(),
    QuotationNo: text('QuotationNo'),
    QuotationDate: timestamp('QuotationDate'),
    PartyID: integer('PartyID').references(() => partyTable.PartyID),
    InquiryNo: varchar('InquiryNo', { length: 255 }),
    InquiryDate: timestamp('InquiryDate'),
    PartyDCNo: varchar('PartyDCNo', { length: 255 }),
    PartyDCDate: timestamp('PartyDCDate'),
    BuyerName: varchar('BuyerName', { length: 255 }),
    BuyerAddress: text('BuyerAddress'),
    BuyerGSTIN: varchar('BuyerGSTIN', { length: 100 }),
    BuyerState: varchar('BuyerState', { length: 100 }),
    BuyerStateCode: varchar('BuyerStateCode', { length: 100 }),
    BuyerPanNo: varchar('BuyerPanNo', { length: 100 }),
    KindlyAttentionTo: text('KindlyAttentionTo'),
    TotalAmtBeforeTax: decimal('TotalAmtBeforeTax', { precision: 15, scale: 2 }),
    GST: decimal('GST', { precision: 15, scale: 2 }),
    TotalGSTTax: decimal('TotalGSTTax', { precision: 15, scale: 2 }),
    TotalAmtAfterTax: decimal('TotalAmtAfterTax', { precision: 15, scale: 2 }),
    TotalInWords: text('TotalInWords'),
    TaxInWords: text('TaxInWords'),
    Remarks: text('Remarks'),
    GrandTotalAmount: decimal('GrandTotalAmount', { precision: 15, scale: 2 }),
    RoundOff: decimal('RoundOff', { precision: 15, scale: 2 }),
    CreatedBy: varchar('CreatedBy', { length: 255 }),
    ModifiedBy: varchar('ModifiedBy', { length: 255 }),
    PreparedBy: varchar('PreparedBy', { length: 255 }),
    Mobile: varchar('Mobile', { length: 100 }),
    PackingCharge: text('PackingCharge'),
    IsGST: boolean('IsGST'),
    DeliveryTime: varchar('DeliveryTime', { length: 255 }),
    NewFOR: varchar('NewFOR', { length: 255 }),
    PaymentTerm: varchar('PaymentTerm', { length: 255 }),
    Warranty: varchar('Warranty', { length: 255 }),
    Validity: varchar('Validity', { length: 255 }),
    Company: varchar('Company', { length: 255 }),
    QuotationType: varchar('QuotationType', { length: 100 }),
    FormType: varchar('FormType', { length: 100 }),
    ModelNo: varchar('ModelNo', { length: 255 }),
    CreatedAt: timestamp('CreatedAt').defaultNow(),
    UpdatedAt: timestamp('UpdatedAt').$onUpdate(() => new Date()),
})

export const quotationDetailTable = pgTable('QuotationDetail', {
    QuotationDetailID: integer('QuotationDetailID').primaryKey().generatedAlwaysAsIdentity(),
    QuotationID: integer('QuotationID').references(() => quotationTable.QuotationID),
    ProductName: varchar('ProductName', { length: 255 }),
    CategoryID: integer('CategoryID').references(() => categoryTable.CategoryID),
    Description: text('Description'),
    HSNACS: varchar('HSNACS', { length: 100 }),
    UOM: varchar('UOM', { length: 100 }),
    Qty: decimal('Qty', { precision: 15, scale: 4 }),
    Rate: decimal('Rate', { precision: 15, scale: 2 }),
    Amount: decimal('Amount', { precision: 15, scale: 2 }),
    Discount: decimal('Discount', { precision: 15, scale: 2 }),
    DiscountVal: decimal('DiscountVal', { precision: 15, scale: 2 }),
    TaxableValue: decimal('TaxableValue', { precision: 15, scale: 2 }),
    GSTRate: decimal('GSTRate', { precision: 5, scale: 2 }),
    GSTAmt: decimal('GSTAmt', { precision: 15, scale: 2 }),
    TotalAmount: decimal('TotalAmount', { precision: 15, scale: 2 }),
    createdAt: timestamp('created_at').defaultNow(),
    updatedAt: timestamp('updated_at').$onUpdate(() => new Date()),
})

export const pumpTypeMasterTable = pgTable('PumpTypeMaster', {
    PumpTypeID: integer('PumpTypeID').primaryKey().generatedAlwaysAsIdentity(),
    PumpTypeName: varchar('PumpTypeName', { length: 255 }).notNull(),
    Company: varchar('Company', { length: 255 }),
})

export const pumpModelMasterTable = pgTable('PumpModelMaster', {
    PumpModelID: integer('PumpModelID').primaryKey().generatedAlwaysAsIdentity(),
    PumpModelName: varchar('PumpModelName', { length: 255 }).notNull(),
    Company: varchar('Company', { length: 255 }),
})

export const suctionPressureMasterTable = pgTable('SuctionPressureMaster', {
    SuctionPressureID: integer('SuctionPressureID').primaryKey().generatedAlwaysAsIdentity(),
    SuctionPressureName: varchar('SuctionPressureName', { length: 255 }).notNull(),
    CompanyName: varchar('CompanyName', { length: 255 }),
})

export const proposalScopeMasterTable = pgTable('ProposalScopeMaster', {
    ScopeID: integer('ScopeID').primaryKey().generatedAlwaysAsIdentity(),
    Description: text('Description'),
})

export const proposalTermsMasterTable = pgTable('ProposalTermsMaster', {
    TermID: integer('TermID').primaryKey().generatedAlwaysAsIdentity(),
    CompanyName: varchar('CompanyName', { length: 255 }),
    TermText: text('TermText'),
    SrNo: integer('SrNo'),
    IsDefault: integer('IsDefault'),
})

export const proposalHistoryTable = pgTable('ProposalHistory', {
    ProposalID: integer('ProposalID').primaryKey().generatedAlwaysAsIdentity(),
    ProposalNumber: varchar('ProposalNumber', { length: 255 }),
    CompanyID: integer('CompanyID').references(() => companyTable.CompanyID),
    PartyID: integer('PartyID').references(() => partyTable.PartyID),
    ProductID: integer('ProductID').references(() => productTable.ProductID),
    PumpTypeID: integer('PumpTypeID').references(() => pumpTypeMasterTable.PumpTypeID),
    PumpModelID: integer('PumpModelID').references(() => pumpModelMasterTable.PumpModelID),
    PumpType: varchar('PumpType', { length: 255 }),
    PumpModel: varchar('PumpModel', { length: 255 }),
    Price: decimal('Price', { precision: 15, scale: 2 }),
    Discount: decimal('Discount', { precision: 15, scale: 2 }),
    DeliveryTime: varchar('DeliveryTime', { length: 255 }),
    ProposalDate: timestamp('ProposalDate'),
    GeneratedBy: varchar('GeneratedBy', { length: 255 }),
    Application: varchar('Application', { length: 255 }),
    FullProductName: varchar('FullProductName', { length: 255 }),
    DischargeCapacity: varchar('DischargeCapacity', { length: 255 }),
    DischargePressure: varchar('DischargePressure', { length: 255 }),
    PumpSPM: varchar('PumpSPM', { length: 255 }),
    BlockMaterial: varchar('BlockMaterial', { length: 255 }),
    ValveAssembly: varchar('ValveAssembly', { length: 255 }),
    PlungerMaterial: varchar('PlungerMaterial', { length: 255 }),
    InletOutlet: varchar('InletOutlet', { length: 255 }),
    SuctionPressure: varchar('SuctionPressure', { length: 255 }),
    MotorHP: varchar('MotorHP', { length: 255 }),
    DriveDetails: varchar('DriveDetails', { length: 255 }),
    FormattedPrice: varchar('FormattedPrice', { length: 255 }),
    PriceInWords: text('PriceInWords'),
    ReferenceNo: varchar('ReferenceNo', { length: 255 }),
    ReferenceDate: varchar('ReferenceDate', { length: 255 }),
    InquiryNo: varchar('InquiryNo', { length: 255 }),
    InquiryDate: varchar('InquiryDate', { length: 255 }),
    BuyerName: varchar('BuyerName', { length: 255 }),
    BuyerAddress: text('BuyerAddress'),
    BuyerGSTIN: varchar('BuyerGSTIN', { length: 100 }),
    BuyerPANNo: varchar('BuyerPANNo', { length: 100 }),
    BuyerState: varchar('BuyerState', { length: 100 }),
    BuyerStateCode: varchar('BuyerStateCode', { length: 100 }),
    KindlyAttentionTo: varchar('KindlyAttentionTo', { length: 255 }),
    MOCDetails: varchar('MOCDetails', { length: 255 }),
    HandlingMaterial: varchar('HandlingMaterial', { length: 255 }),
    Temperature: varchar('Temperature', { length: 255 }),
    PumpSetQuantity: integer('PumpSetQuantity'),
    MotorPrice: decimal('MotorPrice', { precision: 15, scale: 2 }),
    MotorQuantity: integer('MotorQuantity'),
    DiscountNote: varchar('DiscountNote', { length: 255 }),
    CreatedBy: varchar('CreatedBy', { length: 255 }),
    ModifiedBy: varchar('ModifiedBy', { length: 255 }),
    CreatedAt: timestamp('CreatedAt').defaultNow(),
    UpdatedAt: timestamp('UpdatedAt').$onUpdate(() => new Date()),
})

export const proposalTermsHistoryTable = pgTable('ProposalTermsHistory', {
    HistTermID: integer('HistTermID').primaryKey().generatedAlwaysAsIdentity(),
    ProposalID: integer('ProposalID').references(() => proposalHistoryTable.ProposalID),
    SrNo: integer('SrNo'),
    TermText: text('TermText'),
    createdAt: timestamp('created_at').defaultNow(),
    updatedAt: timestamp('updated_at').$onUpdate(() => new Date()),
})

export const proposalScopeHistoryTable = pgTable('ProposalScopeHistory', {
    ScopeID: integer('ScopeID').primaryKey().generatedAlwaysAsIdentity(),
    ProposalID: integer('ProposalID').references(() => proposalHistoryTable.ProposalID),
    SrNo: integer('SrNo'),
    Description: text('Description'),
    createdAt: timestamp('created_at').defaultNow(),
    updatedAt: timestamp('updated_at').$onUpdate(() => new Date()),
})

export const proposalCustomFieldsTable = pgTable('ProposalCustomFields', {
    FieldID: integer('FieldID').primaryKey().generatedAlwaysAsIdentity(),
    ProposalID: integer('ProposalID').references(() => proposalHistoryTable.ProposalID),
    FieldName: varchar('FieldName', { length: 255 }),
    FieldValue: varchar('FieldValue', { length: 255 }),
})

export const proposalExtraProductsTable = pgTable('ProposalExtraProducts', {
    ExtraProductID: integer('ExtraProductID').primaryKey().generatedAlwaysAsIdentity(),
    ProposalID: integer('ProposalID').references(() => proposalHistoryTable.ProposalID),
    SrNo: integer('SrNo'),
    ProductName: varchar('ProductName', { length: 255 }),
    Price: decimal('Price', { precision: 15, scale: 2 }),
    Quantity: integer('Quantity'),
    createdAt: timestamp('created_at').defaultNow(),
    updatedAt: timestamp('updated_at').$onUpdate(() => new Date()),
})
