import { z } from 'zod'

const optionalString = (length?: number) => z.string().max(length ?? 255).nullable().optional()
const optionalDecimal = z.coerce.string().nullable().optional()
const optionalBoolean = z.boolean().nullable().optional()
const optionalTimestamp = z.coerce.date().nullable().optional()

// ── Invoice line item ────────────────────────────────────────────
export const invoiceLineItemModel = z.object({
    ProductName: optionalString(255),
    Description: z.string().nullable().optional(),
    HSNACS: optionalString(100),
    UOM: optionalString(100),
    Qty: optionalDecimal,
    Rate: optionalDecimal,
    IsService: optionalString(50),
    Amount: optionalDecimal,
    Discount: optionalDecimal,
    DiscountVal: optionalDecimal,
    TaxableValue: optionalDecimal,
    CGSTRate: optionalDecimal,
    CGSTAmt: optionalDecimal,
    SGSTRate: optionalDecimal,
    SGSTAmt: optionalDecimal,
    IGSTRate: optionalDecimal,
    IGSTAmt: optionalDecimal,
    TotalAmount: optionalDecimal,
})

// ── Create Invoice ──────────────────────────────────────────────
export const createInvoicePayloadModel = z.object({
    InvoiceNo: z.string().nullable().optional(),
    InvoiceDate: optionalTimestamp,
    PartyID: z.number().int().positive().nullable().optional(),
    ChallanNo: optionalString(255),
    ChallanDate: optionalTimestamp,
    PartyDCNo: optionalString(255),
    PartyDCDate: optionalTimestamp,
    PO: optionalString(255),
    PODate: optionalTimestamp,
    ARNNo: optionalString(255),
    ARNDate: optionalTimestamp,
    TransportationMode: optionalString(255),
    SupplyTo: optionalString(255),
    SupplyStateCode: z.number().int().positive().nullable().optional(),
    ModelNo: optionalString(255),
    AgainstForm: optionalString(255),
    ReceiverName: optionalString(255),
    ReceiverAddress: z.string().nullable().optional(),
    ReceiverGSTIN: optionalString(100),
    ReceiverState: optionalString(100),
    ReceiverStateCode: optionalString(100),
    ReceiverPanNo: optionalString(100),
    ConsigneeName: optionalString(255),
    ConsigneePartyID: z.number().int().positive().nullable().optional(),
    ConsigneeAddress: z.string().nullable().optional(),
    ConsigneeGSTIN: optionalString(100),
    ConsigneeState: optionalString(100),
    ConsigneeStateCode: optionalString(100),
    ConsigneePanNo: optionalString(100),
    IsSameAddress: optionalBoolean,
    TotalAmtBeforeTax: optionalDecimal,
    PackingCharge: optionalDecimal,
    PCGSTRate: optionalDecimal,
    PCGSTAmt: optionalDecimal,
    PSGSTRate: optionalDecimal,
    PSGSTAmt: optionalDecimal,
    PIGSTRate: optionalDecimal,
    PIGSTAmt: optionalDecimal,
    CGST: optionalDecimal,
    SGST: optionalDecimal,
    IGST: optionalDecimal,
    TotalGSTTax: optionalDecimal,
    TotalAmtAfterTax: optionalDecimal,
    GSTReverseCharge: optionalDecimal,
    TotalInWords: z.string().nullable().optional(),
    TaxInWords: z.string().nullable().optional(),
    Remarks: z.string().nullable().optional(),
    GrandTotalAmount: optionalDecimal,
    RoundOff: optionalDecimal,
    Company: optionalString(255),
    InvoiceType: optionalString(100),
    QRCode: z.string().nullable().optional(),
    IRNNo: optionalString(255),
    AckNo: optionalString(255),
    AckDate: optionalString(255),
    TransId: optionalString(255),
    TransName: optionalString(255),
    TransMode: optionalString(255),
    Distance: optionalString(255),
    VehNo: optionalString(255),
    VehType: optionalString(255),
    EwbNo: optionalString(255),
    EwbDt: optionalString(255),
    EwbValidTill: optionalString(255),
    CEWBNo: optionalString(255),
    MultiVehInfo: optionalString(255),
    PlaceOfDel: optionalString(255),
    ShipPin: optionalString(255),
    // Line items
    lineItems: z.array(invoiceLineItemModel).optional(),
})

export const updateInvoicePayloadModel = createInvoicePayloadModel.partial()
